const DATA_URL='data/recalls.json';
const MAP_URL='data/us-states.json';

const STATE_NAMES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming',DC:'District of Columbia'};
const FIPS_TO_ABBR={'01':'AL','02':'AK','04':'AZ','05':'AR','06':'CA','08':'CO','09':'CT','10':'DE','11':'DC','12':'FL','13':'GA','15':'HI','16':'ID','17':'IL','18':'IN','19':'IA','20':'KS','21':'KY','22':'LA','23':'ME','24':'MD','25':'MA','26':'MI','27':'MN','28':'MS','29':'MO','30':'MT','31':'NE','32':'NV','33':'NH','34':'NJ','35':'NM','36':'NY','37':'NC','38':'ND','39':'OH','40':'OK','41':'OR','42':'PA','44':'RI','45':'SC','46':'SD','47':'TN','48':'TX','49':'UT','50':'VT','51':'VA','53':'WA','54':'WV','55':'WI','56':'WY'};

const el=id=>document.getElementById(id);
const statusText=el('statusText'),updatedAt=el('updatedAt'),activeCount=el('activeCount'),highCount=el('highCount'),nationwideCount=el('nationwideCount'),newCount=el('newCount'),topCategory=el('topCategory'),categoryFilters=el('categoryFilters'),stateFilter=el('stateFilter'),agencyFilter=el('agencyFilter'),sortFilter=el('sortFilter'),mapScopeLabel=el('mapScopeLabel'),usMap=el('usMap'),recallLayer=el('recallLayer'),nationwideRail=el('nationwideRail'),leaderboard=el('leaderboard'),recallDialog=el('recallDialog'),dialogContent=el('dialogContent'),dialogClose=el('dialogClose'),mapStage=el('mapStage');

let recalls=[],selectedCategory='All',mapFeatures=[],mapReady=false,mapPath=null,generatedAt=null;
let snapshots={};
try{snapshots=JSON.parse(localStorage.getItem('foodRecallWallSnapshots')||'{}')}catch(_){snapshots={}}

function get(o,...ks){for(const k of ks)if(o&&o[k]!=null&&o[k]!=='')return o[k];return''}
function dateOnly(v){if(!v)return null;const s=String(v);if(/^\d{8}$/.test(s))return new Date(`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T12:00:00`);const d=new Date(s);return Number.isNaN(d.getTime())?null:d}
function daysAgo(d){return d?Math.max(0,Math.floor((Date.now()-d.getTime())/86400000)):9999}
function stripHtml(s){const d=document.createElement('div');d.innerHTML=String(s||'');return d.textContent||''}
function escapeHTML(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function normalizeState(v){const s=String(v||'').trim();if(!s)return'';const upper=s.toUpperCase();if(STATE_NAMES[upper])return upper;for(const[a,n]of Object.entries(STATE_NAMES))if(n.toLowerCase()===s.toLowerCase())return a;return''}
function classifyCategory(text){const t=String(text||'').toLowerCase();if(/beef|steak|veal|pork|ham|sausage|meat|chicken|turkey|poultry|duck/.test(t))return'Meat & Poultry';if(/milk|cheese|cream|butter|yogurt|dairy/.test(t))return'Dairy';if(/fish|salmon|tuna|shrimp|crab|oyster|seafood|shellfish/.test(t))return'Seafood';if(/lettuce|spinach|pepper|tomato|produce|fruit|vegetable|melon|cucumber|sprout/.test(t))return'Produce';if(/cookie|cake|bread|cereal|snack|chip|candy|chocolate|bakery|cracker/.test(t))return'Packaged Foods';if(/allergen|undeclared|peanut|sesame|wheat|soy|egg/.test(t))return'Allergens';if(/drink|juice|water|beverage|coffee|tea/.test(t))return'Beverages';return'Other'}
function parseStates(text){const t=` ${String(text||'').replace(/[.;()]/g,' ')} `;if(/nationwide|all 50 states|national distribution|throughout the united states/i.test(t))return{nationwide:true,states:Object.keys(STATE_NAMES).filter(s=>s!=='DC')};const found=new Set();for(const[abbr,name]of Object.entries(STATE_NAMES)){const nr=new RegExp(`\\b${name.replace(/ /g,'\\s+')}\\b`,'i'),ar=new RegExp(`(?:^|[\\s,;/])${abbr}(?=$|[\\s,;/])`,'i');if(nr.test(t)||ar.test(t))found.add(abbr)}return{nationwide:false,states:[...found]}}
function riskClass(v){const t=String(v||'').toLowerCase();if(t.includes('class i')||t.includes('high'))return'Class I';if(t.includes('class ii')||t.includes('medium'))return'Class II';if(t.includes('class iii')||t.includes('low'))return'Class III';return'Unclassified'}
function computeScore(r){const risk={'Class I':100,'Class II':62,'Class III':34,'Unclassified':45}[r.classification],scope=r.nationwide?45:Math.min(38,r.states.length*2.2),age=daysAgo(r.date),recency=age<=2?30:age<=7?23:age<=30?12:age<=90?5:0;return Math.round(risk+scope+recency+(r.active?12:0))}
function normalizeFDA(x){const distribution=get(x,'distribution_pattern'),geo=parseStates(distribution),r={id:`FDA-${get(x,'event_id','recall_number')}`,agency:'FDA',company:get(x,'recalling_firm')||'Unknown firm',product:get(x,'product_description')||'Food product',reason:get(x,'reason_for_recall')||'See official recall notice.',classification:riskClass(get(x,'classification')),status:get(x,'status')||'Ongoing',active:/ongoing/i.test(get(x,'status')||'Ongoing'),date:dateOnly(get(x,'recall_initiation_date','report_date')),distribution,states:geo.states,nationwide:geo.nationwide,originState:normalizeState(get(x,'state')),recallNumber:get(x,'recall_number','event_id'),url:'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts',source:x};r.category=classifyCategory(`${r.product} ${r.reason}`);r.score=computeScore(r);return r}
function normalizeFSIS(x){const title=stripHtml(get(x,'field_recall_title','recall_title','title','RecallTitle')),description=stripHtml(get(x,'field_recall_summary','recall_description','description','RecallDescription')),distribution=stripHtml(get(x,'field_states','states','impacted_states','distribution','field_recall_distribution')),geo=parseStates(distribution||description),r={id:`FSIS-${get(x,'field_recall_number','recall_number','id','nid','RecallNumber')||title.slice(0,50)}`,agency:'USDA FSIS',company:stripHtml(get(x,'field_recall_company','company_name','company','establishment'))||'USDA-regulated firm',product:title||stripHtml(get(x,'field_product_items','product_description'))||'Meat, poultry, or egg product',reason:stripHtml(get(x,'field_recall_reason','recall_reason','reason'))||description||'See official recall notice.',classification:riskClass(get(x,'field_recall_classification','risk_level','classification','field_risk_level')),status:String(get(x,'field_recall_status','recall_type','status')||'Active'),active:!/closed|complete|inactive/i.test(String(get(x,'field_recall_status','recall_type','status')||'Active')),date:dateOnly(get(x,'field_recall_date','recall_date','date','created','RecallDate')),distribution,states:geo.states,nationwide:geo.nationwide,originState:normalizeState(get(x,'field_establishment_state','establishment_state','state','State')),recallNumber:get(x,'field_recall_number','recall_number','notice_id_number','RecallNumber'),url:get(x,'field_recall_url','recall_url','url','RecallURL')||'https://www.fsis.usda.gov/recalls',source:x};r.category=classifyCategory(`${r.product} ${r.reason}`);r.score=computeScore(r);return r}
async function fetchJSON(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`${url}: ${res.status}`);return res.json()}
function dedupe(arr){const seen=new Set();return arr.filter(r=>{const k=`${r.agency}|${r.recallNumber||r.product}`;if(seen.has(k))return false;seen.add(k);return true})}
function saveSnapshots(){recalls.forEach(r=>{const old=snapshots[r.id];r.deltaStates=old?Math.max(0,r.states.length-old.states):0;snapshots[r.id]={states:r.states.length,score:r.score,ts:Date.now()}});try{localStorage.setItem('foodRecallWallSnapshots',JSON.stringify(snapshots))}catch(_){}}
function setupStateFilter(){stateFilter.innerHTML='<option value="all">ALL STATES</option>'+Object.entries(STATE_NAMES).filter(([a])=>a!=='DC').sort((a,b)=>a[1].localeCompare(b[1])).map(([a,n])=>`<option value="${a}">${n.toUpperCase()}</option>`).join('')}
function baseFiltered(){const agency=agencyFilter.value;return recalls.filter(r=>(selectedCategory==='All'||r.category===selectedCategory)&&(agency==='all'||r.agency===agency))}
function filtered(){const sort=sortFilter.value,state=stateFilter.value,rows=baseFiltered().filter(r=>state==='all'||r.nationwide||r.states.includes(state));rows.sort((a,b)=>sort==='newest'?(b.date||0)-(a.date||0):sort==='scope'?b.states.length-a.states.length:b.score-a.score);return rows}
function render(){renderFilters();renderSummary();renderMap();renderLeaderboard()}
function renderFilters(){const cats=['All',...new Set(recalls.map(r=>r.category))];categoryFilters.innerHTML=cats.map(c=>`<button class="filter-btn ${c===selectedCategory?'active':''}" data-cat="${escapeHTML(c)}">${escapeHTML(c.toUpperCase())}</button>`).join('');document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{selectedCategory=b.dataset.cat;render()}))}
function renderSummary(){const rows=filtered();activeCount.textContent=rows.length.toLocaleString();highCount.textContent=rows.filter(r=>r.classification==='Class I').length;nationwideCount.textContent=rows.filter(r=>r.nationwide).length;newCount.textContent=rows.filter(r=>daysAgo(r.date)<=7).length;const counts={};rows.forEach(r=>counts[r.category]=(counts[r.category]||0)+1);topCategory.textContent=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';const st=stateFilter.value;mapScopeLabel.textContent=st==='all'?'US / ACTIVE RECALLS':`${st} / ${STATE_NAMES[st].toUpperCase()} / ACTIVE RECALLS`}
function stateActivity(rows,a){return rows.filter(r=>r.nationwide||r.states.includes(a))}
function activityClass(n){return n>=10?'activity-4':n>=6?'activity-3':n>=3?'activity-2':n>=1?'activity-1':''}
function abbrForFeature(f){const id=String(f.id);return id.length===2&&STATE_NAMES[id]?id:(FIPS_TO_ABBR[id.padStart(2,'0')]||'')}
function riskSlug(r){return r.classification==='Class I'?'class-i':r.classification==='Class II'?'class-ii':'class-iii'}
function featureCentroid(abbr){const f=mapFeatures.find(x=>abbrForFeature(x)===abbr);if(!f||!mapPath)return null;const c=mapPath.centroid(f);return Number.isFinite(c[0])?c:null}
function originForRecall(r){return r.originState||(!r.nationwide&&r.states.length?r.states[0]:'')}

function drawGeographicMap(){
  if(!mapReady||typeof d3==='undefined')return;
  const svg=d3.select(usMap);svg.selectAll('*').remove();
  const projection=d3.geoAlbersUsa().fitExtent([[28,24],[932,554]],{type:'FeatureCollection',features:mapFeatures});mapPath=d3.geoPath(projection);
  const rows=baseFiltered(),selected=stateFilter.value;
  svg.append('g').selectAll('path').data(mapFeatures).join('path').attr('d',mapPath).attr('class',f=>{const a=abbrForFeature(f),n=a?stateActivity(rows,a).length:0;return`state-path ${activityClass(n)} ${selected!=='all'&&a===selected?'selected':''} ${selected!=='all'&&a!==selected?'dimmed':''}`}).attr('data-state',abbrForFeature).on('click',(event,f)=>{const a=abbrForFeature(f);if(!a)return;stateFilter.value=selected===a?'all':a;render()});
  const labels=mapFeatures.map(f=>({abbr:abbrForFeature(f),c:mapPath.centroid(f)})).filter(d=>d.abbr&&Number.isFinite(d.c[0]));
  svg.append('g').selectAll('text').data(labels).join('text').attr('class','state-label').attr('data-state-label',d=>d.abbr).attr('x',d=>d.c[0]).attr('y',d=>d.c[1]).text(d=>d.abbr);
}

function overlaps(a,b,pad=5){return!(a.x+a.w+pad<b.x||b.x+b.w+pad<a.x||a.y+a.h+pad<b.y||b.y+b.h+pad<a.y)}
function placeCard(r,rank,placed){
  const origin=originForRecall(r),c=featureCentroid(origin);if(!c)return null;
  const sx=recallLayer.clientWidth/960,sy=recallLayer.clientHeight/600;
  const strength=Math.max(0,Math.min(1,(r.score-75)/115));
  const w=Math.round(82+strength*26),h=Math.round(50+strength*12),cx=c[0]*sx,cy=c[1]*sy;
  const W=recallLayer.clientWidth,H=recallLayer.clientHeight;
  const offsets=[[0,0],[34,-30],[-36,-28],[38,30],[-38,31],[0,-58],[0,58],[68,0],[-68,0],[65,-52],[-65,-52],[65,52],[-65,52]];
  for(const[dx,dy]of offsets){const box={x:Math.max(0,Math.min(W-w,cx-w/2+dx)),y:Math.max(0,Math.min(H-h,cy-h/2+dy)),w,h};if(!placed.some(p=>overlaps(box,p)))return{...box,origin}}
  const angle=rank*2.39996,radius=72+Math.floor(rank/8)*26;return{x:Math.max(0,Math.min(W-w,cx-w/2+Math.cos(angle)*radius)),y:Math.max(0,Math.min(H-h,cy-h/2+Math.sin(angle)*radius)),w,h,origin};
}
function makeMarketBlock(r,rank,placed){const p=placeCard(r,rank,placed);if(!p)return'';placed.push(p);const scope=r.nationwide?'NATL':`${r.states.length} ST`;return`<article class="recall-card geo-block ${riskSlug(r)}" data-id="${encodeURIComponent(r.id)}" data-origin="${p.origin}" style="left:${p.x}px;top:${p.y}px;width:${p.w}px;height:${p.h}px;z-index:${40-rank}" title="${escapeHTML(r.company)} — hover to show impacted states"><div class="block-top"><span class="score">${r.score}</span><span class="scope">${scope}</span></div><div class="company">${escapeHTML(r.company)}</div><div class="origin-tag">${p.origin} ORIGIN</div></article>`}
function clearRecallFocus(){document.querySelectorAll('.state-path').forEach(p=>p.classList.remove('hover-dim','recall-impact','recall-origin'));document.querySelectorAll('.state-label').forEach(p=>p.classList.remove('hover-label-impact','hover-label-origin'))}
function focusRecall(r){if(!r)return;const origin=originForRecall(r);document.querySelectorAll('.state-path').forEach(p=>{const a=p.dataset.state;p.classList.add('hover-dim');if(r.nationwide||r.states.includes(a)){p.classList.remove('hover-dim');p.classList.add('recall-impact')}if(a===origin){p.classList.remove('hover-dim');p.classList.add('recall-origin')}});document.querySelectorAll('.state-label').forEach(l=>{const a=l.dataset.stateLabel;if(r.nationwide||r.states.includes(a))l.classList.add('hover-label-impact');if(a===origin)l.classList.add('hover-label-origin')})}
function bindBlockFocus(){document.querySelectorAll('.geo-block').forEach(node=>{const id=decodeURIComponent(node.dataset.id),r=recalls.find(x=>x.id===id);node.addEventListener('mouseenter',()=>focusRecall(r));node.addEventListener('mouseleave',clearRecallFocus);node.addEventListener('focusin',()=>focusRecall(r));node.addEventListener('focusout',clearRecallFocus)})}
function renderMap(){drawGeographicMap();const rows=filtered();requestAnimationFrame(()=>{const market=rows.filter(r=>!r.nationwide&&originForRecall(r)).slice(0,14),placed=[];recallLayer.innerHTML=mapReady?market.map((r,i)=>makeMarketBlock(r,i,placed)).join(''):'';bindRecallClicks();bindBlockFocus()});nationwideRail.innerHTML=rows.filter(r=>r.nationwide).slice(0,8).map(r=>`<div class="national-chip" data-id="${encodeURIComponent(r.id)}"><strong>${r.score}</strong> NATIONWIDE // ${escapeHTML(r.company)}</div>`).join('');bindRecallClicks()}
function renderLeaderboard(){const rows=filtered().slice(0,40);leaderboard.innerHTML=rows.map((r,i)=>`<div class="leader-row" data-id="${encodeURIComponent(r.id)}"><span class="rank">${String(i+1).padStart(2,'0')}</span><strong>${r.score} IDX</strong><span class="${r.classification==='Class I'?'risk-high':r.classification==='Class II'?'risk-medium':'risk-low'}">${r.classification}</span><span>${escapeHTML(r.company)}</span><span class="leader-product">${escapeHTML(r.product)}</span><span>${r.nationwide?'NATL':`${r.states.length} ST`}</span><span class="agency">${r.agency}</span></div>`).join('');bindRecallClicks()}
function bindRecallClicks(){document.querySelectorAll('[data-id]').forEach(node=>node.addEventListener('click',()=>openRecall(decodeURIComponent(node.dataset.id))))}
function openRecall(id){const r=recalls.find(x=>x.id===id);if(!r)return;const origin=originForRecall(r);dialogContent.innerHTML=`<div class="section-code">${r.agency} // ${escapeHTML(r.recallNumber||'RECALL')}</div><div class="dialog-score">${r.score}</div><h2>${escapeHTML(r.product)}</h2><div class="dialog-grid"><div><div class="detail-label">FIRM</div><div class="detail-value">${escapeHTML(r.company)}</div></div><div><div class="detail-label">CLASSIFICATION</div><div class="detail-value">${r.classification}</div></div><div><div class="detail-label">ORIGIN</div><div class="detail-value">${origin?`${origin} — ${STATE_NAMES[origin]}`:'Not reported'}</div></div><div><div class="detail-label">INITIATED</div><div class="detail-value">${r.date?r.date.toLocaleDateString():'Not reported'}</div></div><div><div class="detail-label">SCOPE</div><div class="detail-value">${r.nationwide?'Nationwide':r.states.length?`${r.states.length} states`:'Distribution not parsed'}</div></div></div><div class="detail-label">REASON</div><div class="dialog-reason">${escapeHTML(r.reason)}</div><div class="detail-label" style="margin-top:16px">DISTRIBUTION</div><div class="detail-value">${escapeHTML(r.distribution||r.states.join(', ')||'See official notice')}</div><a class="official-link" href="${escapeHTML(r.url)}" target="_blank" rel="noopener">OPEN OFFICIAL SOURCE ↗</a>`;recallDialog.showModal()}
function showError(msg){mapStage.querySelectorAll('.error-banner').forEach(n=>n.remove());const e=document.createElement('div');e.className='error-banner';e.textContent=msg;mapStage.appendChild(e)}
async function loadData(){statusText.textContent='LOADING CACHE';const[dataResult,mapResult]=await Promise.allSettled([fetchJSON(DATA_URL),fetchJSON(MAP_URL)]);if(dataResult.status==='fulfilled'){const cache=dataResult.value||{};generatedAt=cache.generated_at||null;recalls=[...(cache.fda||[]).map(normalizeFDA),...(cache.fsis||[]).map(normalizeFSIS)];recalls=dedupe(recalls).filter(r=>r.active).sort((a,b)=>b.score-a.score)}if(mapResult.status==='fulfilled'&&typeof topojson!=='undefined'){const us=mapResult.value;mapFeatures=topojson.feature(us,us.objects.states).features.filter(f=>STATE_NAMES[FIPS_TO_ABBR[String(f.id).padStart(2,'0')]]||STATE_NAMES[String(f.id)]);mapReady=true}setupStateFilter();saveSnapshots();render();if(recalls.length){statusText.textContent='LOCAL DATA';updatedAt.textContent=generatedAt?new Date(generatedAt).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}else{statusText.textContent='CACHE WAITING';showError('Local data cache is empty. GitHub Actions is populating it now.')}if(!mapReady)showError('Local map cache is not ready yet. GitHub Actions will populate it.')}

agencyFilter.addEventListener('change',render);sortFilter.addEventListener('change',render);stateFilter.addEventListener('change',render);dialogClose.addEventListener('click',()=>recallDialog.close());window.addEventListener('resize',()=>{if(mapReady)renderMap()});
loadData().catch(err=>{statusText.textContent='CACHE ERROR';showError('Local cache could not be loaded.');console.error(err)});
